

set_ccopt_property buffer_cells { CLKBUFX20 CLKBUFX4 CLKBUFX16 CLKBUFX6 CLKBUFX3 CLKBUFX12 CLKBUFX8 CLKBUFX2 }
set_ccopt_property inverter_cells { CLKINVX12 CLKINVX8 CLKINVX2 CLKINVX20 CLKINVX4 CLKINVX1 CLKINVX16 CLKINVX6 CLKINVX3 }
